import turtle
import math
#The program Draw Mercedes car symbol
def draw_mercedes():
    turtle.up()
    turtle.goto(0,-50)
    turtle.down()
    turtle.circle(50)
    turtle.up()
    turtle.left(90)
    turtle.forward(50)
    turtle.down()
    turtle.forward(50)
    turtle.up()
    turtle.right(180)
    turtle.forward(50)
    turtle.down()
    turtle.left(60)
    turtle.forward(50)
    turtle.backward(50)
    turtle.right(120)
    turtle.forward(50)
#The program Draw a smily
def draw_smiley():
   turtle.up()
   turtle.goto(-50,0)
   turtle.down()
   turtle.circle(50)
   turtle.up()
   turtle.goto(-70, 60)
   turtle.down()
   turtle.circle(10)
   turtle.up()
   turtle.goto(-30, 60)
   turtle.down()
   turtle.circle(10)
   turtle.up()
   turtle.goto(-50, 20)
   turtle.down()
   turtle.circle(20,90)
   turtle.up()
   turtle.goto(-50, 20)
   turtle.setheading(180)
   turtle.down()
   turtle.circle(-20, 90)
# The program draw a larva with number of links  which the program gets for input
def draw_centipede(n):
    draw_smiley()
    turtle.up()
    turtle.goto((-75),(11/6*50))
    turtle.setheading(90)
    turtle.down()
    turtle.forward(25)
    turtle.up()
    turtle.goto((-25),11/6*50)
    turtle.setheading(90)
    turtle.down()
    turtle.forward(25)
    turtle.up()
    for i in range(n):
        turtle.goto(i*100+50,0)
        turtle.setheading(0)
        turtle.down()
        turtle.circle(50)
        turtle.up()
        turtle.setheading(90)
        turtle.goto(100*i + 25, (-1/3 * 50))
        turtle.down()
        turtle.forward(25)
        turtle.up()
        turtle.goto(100 * i + 75, (-1 / 3 * 50))
        turtle.down()
        turtle.forward(25)
        turtle.up()
#  The program Draw a regular polygon with n sides of length l
def draw_regular_polygon(n, l):
    for i in range (n):
        turtle.left(360/n)
        turtle.forward(l)
# The program gets two lists which stand for the x,y coordinates, and connect them to a poligon.
def connect_all_pairs(x, y):
    turtle.up()
    turtle.goto(x[0],y[0])
    turtle.down()
    for i in range (len(x)):
      for j in range (len(x)):
        turtle.goto(x[i],y[i])
        turtle.goto(x[j],y[j])
    turtle.done()
